version: '3.7'
services:
  my-todo-server:
    container_name: my-todo-server
    restart: unless-stopped
    image: my-todo-server:latest
    ports:
      - "6056:8080"
    networks:
      - micro-cloud-network
    volumes:
      - .logs/my-todo/:/logs
networks:
  micro-cloud-network:
    name: micro-cloud-network
    driver: bridge