version: '3.7'
services:
  my-todo-backend:
    container_name: my-todo-backend
    restart: unless-stopped
    image: todo-backend:latest
    ports:
      - "6056:8080"
    networks:
      - micro-cloud-network
    volumes:
      - . logs/my-todo/:/logs
networks:
  micro-cloud-network:
    name: micro-cloud-network
    driver: bridge